app = "discord-game-sg6k0a"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  DATABASE_PATH = "/data/heist-bank.sqlite"

[processes]
  app = "npm run start:prod"

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ["app"]

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
